import "./globals.css";
import type { Metadata } from "next";
import { Libre_Baskerville } from "next/font/google";
import styles from "./styles.layout.module.scss";
import Link from "next/link";

const font = Libre_Baskerville({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${font.className} pb-8`}>
        <header className={styles.header}>
          <div className="l-wrapper">
            <div className="flex justify-end">
              <div className="mr-auto">
                <a className={styles.logo} href="/">
                  M
                </a>
              </div>
              <nav>
                <ul>
                  <li className="inline-block mx-1">
                    <Link href="/map">Map</Link>
                  </li>
                  <li className="inline-block mx-1">
                    <Link href="/crosswords">Crosswords</Link>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </header>
        <main>
          <div className="l-wrapper">{children}</div>
        </main>
      </body>
    </html>
  );
}
