import { Matrix15x15, CellContents, Clues } from "./types";

// prettier-ignore
export const solution: Matrix15x15<CellContents> = [
  ["I", "D", "L", "Y", null, "E", "G", "G", "S", null, "S", "A", "C", "H", "A"],
  ["R", "I", "A", "A", null, "E", "U", "R", "O", null, "E", "M", "A", "I", "L"],
  ["M", "A", "R", "K", "A", "N", "S", "A", "S", null, "M", "C", "G", "E", "E"],
  ["A", "L", "B", "U", "S", null, null, "M", "A", "C", "I", null, "E", "S", "S"],
  [null, null, null, "T", "E", "N", "A", "M", null, "A", "H", "A", null, null, null],
  ["V", "A", "R", null, "A", "B", "B", "Y", "S", "T", "A", "N", "D", "E", "R"],
  ["I", "D", "E", "S", null, "C", "A", "S", "H", null, "R", "A", "I", "M", "I"],
  ["C", "O", "M", "P", "A", "S", "S", null, "O", "L", "D", "M", "A", "I", "D"],
  ["A", "B", "O", "R", "G", null, "I", "G", "G", "Y", null, "E", "R", "L", "E"],
  ["R", "O", "W", "A", "N", "G", "C", "H", "U", "N", "G", null, "Y", "E", "R"],
  [null, null, null, "Y", "O", "U", null, "A", "N", "N", "A", "L", null, null, null],
  ["R", "S", "T", null, "S", "T", "A", "N", null, null, "P", "H", "A", "G", "E"],
  ["I", "C", "A", "N", "T", null, "S", "I", "L", "A", "S", "A", "G", "N", "A"],
  ["T", "U", "C", "C", "I", null, "H", "A", "I", "M", null, "S", "O", "A", "R"],
  ["A", "D", "H", "O", "C", null, "E", "N", "D", "S", null, "A", "G", "T", "S"],
];

export const clues: Clues = {
  across: [
    `Inactively`,
    `Urges`,
    `___ Baron Cohen`,
    `Diamond, Platinum, and Gold certifiers: Abbr`,
    `___zone, with Finland and France, but not Sweden or Switzerland`,
    `What many meetings could have been`,
    `Sea to a Spaniard + Dorothy's home state`,
    `"___ and Me!"`,
    `___ Dumbledore`,
    `Bookout of "16 and Pregnant" and "Teen Mom"`,
    `Dangerous type of curve, maybe`,
    `Mid-morning hour`,
    `"Take on Me" band`,
    `Soccer replay official, for short`,
    `You may find one in a 6 pack + Onlooker`,
    `Mid-March hazard`,
    `It's cold and hard`,
    `Director of "The Evil Dead" and "The Quick and the Dead"`,
    `Its needle always points North`,
    `Mary's alternate reality fate in "It's a Wonderful Life"`,
    `Seven of Nine, for one`,
    `Leader of a band of Stooges?`,
    `Writer ___ Stanley Gardner`,
    `___ Khanna (California's 17th) + "Everybody Have Fun Tonight" band`,
    `"___ Blues" from The Beatles "The Beatles"`,
    `The pronoun of the person doing this puzzle?`,
    `Record of the year?`,
    `What may sometimes come between Q and U in English?`,
    `NBA's Van Gundy`,
    `Germicidal germ`,
    `"This's too much"`,
    `Yucatan Yes + Garfield's Favorite Food`,
    `Director and Star of Big Night (1996)`,
    `Group of Women in Music (Pt III)`,
    `John Ashcroft's "Let the Eagle ___"`,
    `As necessary`,
    `Where hairs are usually split`,
    `Some F.B.I`,
  ],
  down: [
    `Strongest Hurricane of 2017`,
    `Clock face, or a big name in soap`,
    `Meaty Southeast Asian Salad`,
    `Official language of the Russian Republic of Sakha`,
    `Nighttime, poetically`,
    `Astronaut Grissom`,
    `Music awards ceremony`,
    `Only three-time member of the 60 home run club`,
    `Like Manchego, Gouda or Cheddar`,
    `Station for Mad Men`,
    `Nick of The Wicker Man`,
    `Races, archaically`,
    `Some are browns, some are pales, some are reals, all are...`,
    `Toward the ocean`,
    `Creature with nine lives`,
    `___ Saturday Night (Original title of SNL)`,
    `Unable to walk`,
    `"What's in ___?"`,
    `Anglican parish priest`,
    `Chipotle marinade`,
    `Fix the lawn, maybe`,
    `Ancient Japanese military dictator`,
    `Log`,
    `Hirsch of "Into the Wild"`,
    `1994 Slam Dunk Contest Champion J.R.`,
    `"Say it, don't ___ it"`,
    `One who doesn't claim to know`,
    `Red Sox Hall of Famer Fred`,
    `Neighbor of an Ivorian and a Togolese`,
    `A certain type of feeling`,
    `Breaks in continuity`,
    `Capital of Tibet`,
    `A lovely meter maid`,
    `A type of surface to surface missile`,
    `RPM measurer, for short`,
    `Tennis champion and AIDS activist Arthur`,
    `Wide-eyed`,
    `A tiny insect that mates in a swarm`,
    `"I'm all ___"`,
    `Sgt or Cpl`,
    `One of three around the eye of 22-Down`,
    `Trans and Pan, for two`,
  ],
};
